services:
  rest_api_service:
    image: rest_api_book_lib_docker:latest
    hostname: rest_api
    container_name: rest_api_book_lib_docker
    ports:
      - '5000:5000'

  jenkins:
    image: jenkins_with_autotests
    hostname: jenkins
    container_name: jenkins_running_autotests
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - rest_api_service
